blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/joelbutcher/socialstream/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Support question
    url: https://github.com/joelbutcher/socialstream/discussions/new?category=q-a
    about: Ask the community for help
